# Compile Code for Project Data Refurgee by Data Engineers Team

## Dataset name = AFR-SG Member_Volunteer List (18 June 2022)

Dictionaries
1.  __rawdata__        - The dataset from Digilabs
2.  __rawdata1__      - The header column name change

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
%matplotlib inline

If you python not yet instal wordcloud

Write the code below and restart the jupyter notebbok

_pip install wordcloud_

In [2]:
# Import raw data 
# raw data in excel from
rawdata = pd.read_excel("AFR-SG Member_Volunteer List (18 June 2022).xlsx")

In [3]:
rawdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438 entries, 0 to 437
Data columns (total 10 columns):
 #   Column                                                                                                                           Non-Null Count  Dtype
---  ------                                                                                                                           --------------  -----
 0   Source                                                                                                                           438 non-null    int64
 1   Timestamp                                                                                                                        438 non-null    datetime64[ns]
 2   Gender                                                                                                                           437 non-null    object
 3   Age group / Year of Birth                                                                                                        438 non-null    object
 4   Nationality (please indicate)                                                                                                    438 non-null    object
 5   Occupation/ Job title                                                                                                            438 non-null    object
 6   Why did you join AFR-SG? /
How do you wish to contribute to the cause?                                                          438 non-null    object
 7   What are some of your areas of interest(s)?                                                                                      437 non-null    object
 8   Do you have any skills, experiences, strengths that you could offer to the group? (please only choose what is relevant to you)   438 non-null    object
 9   How much time do you have available for volunteering? (e.g. 1 - 2 hours a week; weekdays; evenings; weekends; shifts; flexible)  421 non-null    object
dtypes: datetime64[ns](1), int64(1), object(8)
memory usage: 34.3+ KB

In [4]:
rawdata.head()

,Source,Timestamp,Gender,Age group / Year of Birth,Nationality (please indicate),Occupation/ Job title,Why did you join AFR-SG? / \nHow do you wish to contribute to the cause?,What are some of your areas of interest(s)?,"Do you have any skills, experiences, strengths that you could offer to the group? (please only choose what is relevant to you)",How much time do you have available for volunteering? (e.g. 1 - 2 hours a week; weekdays; evenings; weekends; shifts; flexible)
0,1,2016-05-29 19:58:05.562,Male,25-34,Singaporean,Programme Officer,Believe that refugees deserve equal opportunit...,"Policy change/reform, public outreach, awarene...","Advocacy / Campaigning, Fundraising / Partners...",Evenings; occasionally on weekends
1,1,2016-05-29 20:12:14.090,Female,19-24,Indian,Student,"Learn more about refugees and related issues, ...",Political science,Administration (i.e. data entry / management /...,Flexible
2,1,2016-05-29 20:15:43.953,Male,19-24,Singaporean,Student,"Learn more about refugees and related issues, ...",Law,Policy,flexible
3,1,2016-05-29 20:29:18.128,Male,19-24,Singaporean,Student,"Learn more about refugees and related issues, ...",Raising awareness of the refugee situation loc...,Administration (i.e. data entry / management /...,"flexible, mostly afternoons"
4,1,2016-05-29 20:37:44.177,Female,19-24,Singaporean,Researcher,"Learn more about refugees and related issues, ...","Gender, sociology, human rights and development","Advocacy / Campaigning, Education (i.e. mentor...",Flexible

In [5]:
rawdata.dtypes

Source                                                                                                                                      int64
Timestamp                                                                                                                          datetime64[ns]
Gender                                                                                                                                     object
Age group / Year of Birth                                                                                                                  object
Nationality (please indicate)                                                                                                              object
Occupation/ Job title                                                                                                                      object
Why did you join AFR-SG? / \nHow do you wish to contribute to the cause?                                                                   object
What are some of your areas of interest(s)?                                                                                                object
Do you have any skills, experiences, strengths that you could offer to the group? (please only choose what is relevant to you)             object
How much time do you have available for volunteering? (e.g. 1 - 2 hours a week; weekdays; evenings; weekends; shifts; flexible)            object
dtype: object

# Wrangling and Cleaning
__Cleaning needs__

1. Change the header name to easy to read and code.
2. Source change to int.
3. For header "Age group / Year of Birth" use range and put in A, B, C.
4. For the last four header take the important word as the main, or put in different category because it looks like a multiple choice, so make sure to change to other coloumn based on choice or you can group based on choice for easy reading, manipulation, and modelling.
5. No need to delete null/NaN data because the data to small to ignore the rest of column.

#### Rename the header

In [6]:
rawdata.head()

,Source,Timestamp,Gender,Age group / Year of Birth,Nationality (please indicate),Occupation/ Job title,Why did you join AFR-SG? / \nHow do you wish to contribute to the cause?,What are some of your areas of interest(s)?,"Do you have any skills, experiences, strengths that you could offer to the group? (please only choose what is relevant to you)",How much time do you have available for volunteering? (e.g. 1 - 2 hours a week; weekdays; evenings; weekends; shifts; flexible)
0,1,2016-05-29 19:58:05.562,Male,25-34,Singaporean,Programme Officer,Believe that refugees deserve equal opportunit...,"Policy change/reform, public outreach, awarene...","Advocacy / Campaigning, Fundraising / Partners...",Evenings; occasionally on weekends
1,1,2016-05-29 20:12:14.090,Female,19-24,Indian,Student,"Learn more about refugees and related issues, ...",Political science,Administration (i.e. data entry / management /...,Flexible
2,1,2016-05-29 20:15:43.953,Male,19-24,Singaporean,Student,"Learn more about refugees and related issues, ...",Law,Policy,flexible
3,1,2016-05-29 20:29:18.128,Male,19-24,Singaporean,Student,"Learn more about refugees and related issues, ...",Raising awareness of the refugee situation loc...,Administration (i.e. data entry / management /...,"flexible, mostly afternoons"
4,1,2016-05-29 20:37:44.177,Female,19-24,Singaporean,Researcher,"Learn more about refugees and related issues, ...","Gender, sociology, human rights and development","Advocacy / Campaigning, Education (i.e. mentor...",Flexible

In [7]:
# Rename the header
rawdata1 = rawdata.rename(index=str, columns={"Age group / Year of Birth": "Age",
                                              "Nationality (please indicate)": "Nationality",
                                              "Occupation/ Job title" : "Job",
                                              "Why did you join AFR-SG? / \nHow do you wish to contribute to the cause?": "Reason/Contribute",
                                              "What are some of your areas of interest(s)?": "Interest",
                                              "Do you have any skills, experiences, strengths that you could offer to the group? (please only choose what is relevant to you)": "Skills/Experiences/Strengths",
                                              "How much time do you have available for volunteering? (e.g. 1 - 2 hours a week; weekdays; evenings; weekends; shifts; flexible)": "Available Time"})
rawdata1.head()

,Source,Timestamp,Gender,Age,Nationality,Job,Reason/Contribute,Interest,Skills/Experiences/Strengths,Available Time
0,1,2016-05-29 19:58:05.562,Male,25-34,Singaporean,Programme Officer,Believe that refugees deserve equal opportunit...,"Policy change/reform, public outreach, awarene...","Advocacy / Campaigning, Fundraising / Partners...",Evenings; occasionally on weekends
1,1,2016-05-29 20:12:14.090,Female,19-24,Indian,Student,"Learn more about refugees and related issues, ...",Political science,Administration (i.e. data entry / management /...,Flexible
2,1,2016-05-29 20:15:43.953,Male,19-24,Singaporean,Student,"Learn more about refugees and related issues, ...",Law,Policy,flexible
3,1,2016-05-29 20:29:18.128,Male,19-24,Singaporean,Student,"Learn more about refugees and related issues, ...",Raising awareness of the refugee situation loc...,Administration (i.e. data entry / management /...,"flexible, mostly afternoons"
4,1,2016-05-29 20:37:44.177,Female,19-24,Singaporean,Researcher,"Learn more about refugees and related issues, ...","Gender, sociology, human rights and development","Advocacy / Campaigning, Education (i.e. mentor...",Flexible

#### Change the data types

In [8]:
# use the rawdata1
rawdata1["Source"]=rawdata1["Source"].astype(int)

In [9]:
rawdata1.dtypes

Source                                   int32
Timestamp                       datetime64[ns]
Gender                                  object
Age                                     object
Nationality                             object
Job                                     object
Reason/Contribute                       object
Interest                                object
Skills/Experiences/Strengths            object
Available Time                          object
dtype: object

In [10]:
rawdata1.head()

,Source,Timestamp,Gender,Age,Nationality,Job,Reason/Contribute,Interest,Skills/Experiences/Strengths,Available Time
0,1,2016-05-29 19:58:05.562,Male,25-34,Singaporean,Programme Officer,Believe that refugees deserve equal opportunit...,"Policy change/reform, public outreach, awarene...","Advocacy / Campaigning, Fundraising / Partners...",Evenings; occasionally on weekends
1,1,2016-05-29 20:12:14.090,Female,19-24,Indian,Student,"Learn more about refugees and related issues, ...",Political science,Administration (i.e. data entry / management /...,Flexible
2,1,2016-05-29 20:15:43.953,Male,19-24,Singaporean,Student,"Learn more about refugees and related issues, ...",Law,Policy,flexible
3,1,2016-05-29 20:29:18.128,Male,19-24,Singaporean,Student,"Learn more about refugees and related issues, ...",Raising awareness of the refugee situation loc...,Administration (i.e. data entry / management /...,"flexible, mostly afternoons"
4,1,2016-05-29 20:37:44.177,Female,19-24,Singaporean,Researcher,"Learn more about refugees and related issues, ...","Gender, sociology, human rights and development","Advocacy / Campaigning, Education (i.e. mentor...",Flexible

#### Change The Timestamp to Date and Time

In [11]:
rawdata1.head()

,Source,Timestamp,Gender,Age,Nationality,Job,Reason/Contribute,Interest,Skills/Experiences/Strengths,Available Time
0,1,2016-05-29 19:58:05.562,Male,25-34,Singaporean,Programme Officer,Believe that refugees deserve equal opportunit...,"Policy change/reform, public outreach, awarene...","Advocacy / Campaigning, Fundraising / Partners...",Evenings; occasionally on weekends
1,1,2016-05-29 20:12:14.090,Female,19-24,Indian,Student,"Learn more about refugees and related issues, ...",Political science,Administration (i.e. data entry / management /...,Flexible
2,1,2016-05-29 20:15:43.953,Male,19-24,Singaporean,Student,"Learn more about refugees and related issues, ...",Law,Policy,flexible
3,1,2016-05-29 20:29:18.128,Male,19-24,Singaporean,Student,"Learn more about refugees and related issues, ...",Raising awareness of the refugee situation loc...,Administration (i.e. data entry / management /...,"flexible, mostly afternoons"
4,1,2016-05-29 20:37:44.177,Female,19-24,Singaporean,Researcher,"Learn more about refugees and related issues, ...","Gender, sociology, human rights and development","Advocacy / Campaigning, Education (i.e. mentor...",Flexible

In [12]:
rawdata1['Date'] = [d.date() for d in rawdata1['Timestamp']]
rawdata1['Time'] = [d.time() for d in rawdata1['Timestamp']]

In [13]:
rawdata1.head()

,Source,Timestamp,Gender,Age,Nationality,Job,Reason/Contribute,Interest,Skills/Experiences/Strengths,Available Time,Date,Time
0,1,2016-05-29 19:58:05.562,Male,25-34,Singaporean,Programme Officer,Believe that refugees deserve equal opportunit...,"Policy change/reform, public outreach, awarene...","Advocacy / Campaigning, Fundraising / Partners...",Evenings; occasionally on weekends,2016-05-29,19:58:05.562000
1,1,2016-05-29 20:12:14.090,Female,19-24,Indian,Student,"Learn more about refugees and related issues, ...",Political science,Administration (i.e. data entry / management /...,Flexible,2016-05-29,20:12:14.090000
2,1,2016-05-29 20:15:43.953,Male,19-24,Singaporean,Student,"Learn more about refugees and related issues, ...",Law,Policy,flexible,2016-05-29,20:15:43.953000
3,1,2016-05-29 20:29:18.128,Male,19-24,Singaporean,Student,"Learn more about refugees and related issues, ...",Raising awareness of the refugee situation loc...,Administration (i.e. data entry / management /...,"flexible, mostly afternoons",2016-05-29,20:29:18.128000
4,1,2016-05-29 20:37:44.177,Female,19-24,Singaporean,Researcher,"Learn more about refugees and related issues, ...","Gender, sociology, human rights and development","Advocacy / Campaigning, Education (i.e. mentor...",Flexible,2016-05-29,20:37:44.177000

In [14]:
new_cols = ["Source", "Timestamp", "Date", "Time", "Gender", "Age", "Nationality", "Job", "Reason/Contribute", "Interest",
            "Skills/Experiences/Strengths", "Available Time"]
rawdata1=rawdata1[new_cols]

In [15]:
rawdata1.head()

,Source,Timestamp,Date,Time,Gender,Age,Nationality,Job,Reason/Contribute,Interest,Skills/Experiences/Strengths,Available Time
0,1,2016-05-29 19:58:05.562,2016-05-29,19:58:05.562000,Male,25-34,Singaporean,Programme Officer,Believe that refugees deserve equal opportunit...,"Policy change/reform, public outreach, awarene...","Advocacy / Campaigning, Fundraising / Partners...",Evenings; occasionally on weekends
1,1,2016-05-29 20:12:14.090,2016-05-29,20:12:14.090000,Female,19-24,Indian,Student,"Learn more about refugees and related issues, ...",Political science,Administration (i.e. data entry / management /...,Flexible
2,1,2016-05-29 20:15:43.953,2016-05-29,20:15:43.953000,Male,19-24,Singaporean,Student,"Learn more about refugees and related issues, ...",Law,Policy,flexible
3,1,2016-05-29 20:29:18.128,2016-05-29,20:29:18.128000,Male,19-24,Singaporean,Student,"Learn more about refugees and related issues, ...",Raising awareness of the refugee situation loc...,Administration (i.e. data entry / management /...,"flexible, mostly afternoons"
4,1,2016-05-29 20:37:44.177,2016-05-29,20:37:44.177000,Female,19-24,Singaporean,Researcher,"Learn more about refugees and related issues, ...","Gender, sociology, human rights and development","Advocacy / Campaigning, Education (i.e. mentor...",Flexible

In [16]:
# Delete Timestamp and time
rawdata1 = rawdata1.drop(rawdata1.columns[[1, 3]], axis=1)
rawdata1.head()

,Source,Date,Gender,Age,Nationality,Job,Reason/Contribute,Interest,Skills/Experiences/Strengths,Available Time
0,1,2016-05-29,Male,25-34,Singaporean,Programme Officer,Believe that refugees deserve equal opportunit...,"Policy change/reform, public outreach, awarene...","Advocacy / Campaigning, Fundraising / Partners...",Evenings; occasionally on weekends
1,1,2016-05-29,Female,19-24,Indian,Student,"Learn more about refugees and related issues, ...",Political science,Administration (i.e. data entry / management /...,Flexible
2,1,2016-05-29,Male,19-24,Singaporean,Student,"Learn more about refugees and related issues, ...",Law,Policy,flexible
3,1,2016-05-29,Male,19-24,Singaporean,Student,"Learn more about refugees and related issues, ...",Raising awareness of the refugee situation loc...,Administration (i.e. data entry / management /...,"flexible, mostly afternoons"
4,1,2016-05-29,Female,19-24,Singaporean,Researcher,"Learn more about refugees and related issues, ...","Gender, sociology, human rights and development","Advocacy / Campaigning, Education (i.e. mentor...",Flexible

#### Change Gender to use 1, 2 or 3

In [17]:
rawdata1.head()

,Source,Date,Gender,Age,Nationality,Job,Reason/Contribute,Interest,Skills/Experiences/Strengths,Available Time
0,1,2016-05-29,Male,25-34,Singaporean,Programme Officer,Believe that refugees deserve equal opportunit...,"Policy change/reform, public outreach, awarene...","Advocacy / Campaigning, Fundraising / Partners...",Evenings; occasionally on weekends
1,1,2016-05-29,Female,19-24,Indian,Student,"Learn more about refugees and related issues, ...",Political science,Administration (i.e. data entry / management /...,Flexible
2,1,2016-05-29,Male,19-24,Singaporean,Student,"Learn more about refugees and related issues, ...",Law,Policy,flexible
3,1,2016-05-29,Male,19-24,Singaporean,Student,"Learn more about refugees and related issues, ...",Raising awareness of the refugee situation loc...,Administration (i.e. data entry / management /...,"flexible, mostly afternoons"
4,1,2016-05-29,Female,19-24,Singaporean,Researcher,"Learn more about refugees and related issues, ...","Gender, sociology, human rights and development","Advocacy / Campaigning, Education (i.e. mentor...",Flexible

In [18]:
rawdata1.loc[rawdata1["Gender"]=="Male", ["Gender"]]=1
rawdata1.loc[rawdata1["Gender"]=="Female", ["Gender"]]=2
rawdata1.loc[rawdata1["Gender"]=="Prefer not to disclose", ["Gender"]]=3
rawdata1.loc[rawdata1["Gender"]=="", ["Gender"]]=4

In [19]:
rawdata1.head()

,Source,Date,Gender,Age,Nationality,Job,Reason/Contribute,Interest,Skills/Experiences/Strengths,Available Time
0,1,2016-05-29,1,25-34,Singaporean,Programme Officer,Believe that refugees deserve equal opportunit...,"Policy change/reform, public outreach, awarene...","Advocacy / Campaigning, Fundraising / Partners...",Evenings; occasionally on weekends
1,1,2016-05-29,2,19-24,Indian,Student,"Learn more about refugees and related issues, ...",Political science,Administration (i.e. data entry / management /...,Flexible
2,1,2016-05-29,1,19-24,Singaporean,Student,"Learn more about refugees and related issues, ...",Law,Policy,flexible
3,1,2016-05-29,1,19-24,Singaporean,Student,"Learn more about refugees and related issues, ...",Raising awareness of the refugee situation loc...,Administration (i.e. data entry / management /...,"flexible, mostly afternoons"
4,1,2016-05-29,2,19-24,Singaporean,Researcher,"Learn more about refugees and related issues, ...","Gender, sociology, human rights and development","Advocacy / Campaigning, Education (i.e. mentor...",Flexible

#### Change Age Header to use same format

In [20]:
rawdata1["Age"].value_counts()

25-34       182
19-24       175
35-44        51
45-54        14
> 18          6
2005          3
2004          2
< 55          1
1968          1
1/8/1999      1
1012000       1
1965          1
Name: Age, dtype: int64

__The data  have different format__, so change the same format. Change the year to range so it will made easier to cluster

In [21]:
rawdata1.head()

,Source,Date,Gender,Age,Nationality,Job,Reason/Contribute,Interest,Skills/Experiences/Strengths,Available Time
0,1,2016-05-29,1,25-34,Singaporean,Programme Officer,Believe that refugees deserve equal opportunit...,"Policy change/reform, public outreach, awarene...","Advocacy / Campaigning, Fundraising / Partners...",Evenings; occasionally on weekends
1,1,2016-05-29,2,19-24,Indian,Student,"Learn more about refugees and related issues, ...",Political science,Administration (i.e. data entry / management /...,Flexible
2,1,2016-05-29,1,19-24,Singaporean,Student,"Learn more about refugees and related issues, ...",Law,Policy,flexible
3,1,2016-05-29,1,19-24,Singaporean,Student,"Learn more about refugees and related issues, ...",Raising awareness of the refugee situation loc...,Administration (i.e. data entry / management /...,"flexible, mostly afternoons"
4,1,2016-05-29,2,19-24,Singaporean,Researcher,"Learn more about refugees and related issues, ...","Gender, sociology, human rights and development","Advocacy / Campaigning, Education (i.e. mentor...",Flexible

In [22]:
# Change the range that have space
rawdata1.loc[rawdata1['Age']=="19 - 24", ['Age']]="19-24"
rawdata1.loc[rawdata1['Age']=="25 - 34", ['Age']]="25-34"
rawdata1.loc[rawdata1['Age']=="35 - 44", ['Age']]="35-44"
rawdata1.loc[rawdata1['Age']=="45 - 54", ['Age']]="45-54 "

In [23]:
rawdata1["Age"].value_counts()

25-34       182
19-24       175
35-44        51
45-54        14
> 18          6
2005          3
2004          2
< 55          1
1968          1
1/8/1999      1
1012000       1
1965          1
Name: Age, dtype: int64

In [24]:
# Change all data to range
rawdata1.loc[rawdata1["Age"]=="> 18", ["Age"]]=">=18"
rawdata1.loc[rawdata1["Age"]==2004.0, ["Age"]]=">=18"
rawdata1.loc[rawdata1["Age"]==2005.0, ["Age"]]="<18"
rawdata1.loc[rawdata1["Age"]=="< 55", ["Age"]]="45-54"
rawdata1.loc[rawdata1["Age"]=="<55", ["Age"]]="45-54"
rawdata1.loc[rawdata1["Age"]==1968.0, ["Age"]]="45-54"
rawdata1.loc[rawdata1["Age"]=="1/8/1999", ["Age"]]="19-24"
rawdata1.loc[rawdata1["Age"]==1012000.0, ["Age"]]="19-24"
rawdata1.loc[rawdata1["Age"]==1965.0, ["Age"]]=">55"
rawdata1.loc[rawdata1["Age"]=="01_01_2000", ["Age"]]="<18"

In [25]:
rawdata1["Age"].value_counts()

25-34    182
19-24    177
35-44     51
45-54     16
>=18       8
<18        3
>55        1
Name: Age, dtype: int64

In [26]:
# Change the datatypes to float
for a in rawdata1.index:
    try:
        rawdata1.loc[a, "Age group / Year of Birth"]=float(rawdata1["Age group / Year of Birth"][a])
    except:
        pass

In [27]:
# Find all the data in columns age that have types float
age_1018 = [i for i in range(10,18)]
age_1924 = [i for i in range(19,25)]
age_2534 = [i for i in range(25,35)]
age_3544 = [i for i in range(35,45)]
age_4554 = [i for i in range(45,54)]
age_5560 = [i for i in range(55,60)]
for a in rawdata1.index:
    if type(rawdata1["Age"][a])==float:
        if (2022.0-rawdata1["Age"][a] in age_1018):
            rawdata1.loc[a, ["Age"]]="10-18"
            continue
        if (2022.0-rawdata1["Age"][a] in age_1924):
            rawdata1.loc[a, ["Age"]]="19-24"
            continue
        if (2022.0-rawdata1["Age"][a] in age_2534):
            rawdata1.loc[a, ["Age"]]="25-34"
            continue
        if (2022.0-rawdata1["Age"][a] in age_3544):
            rawdata1.loc[a, ["Age"]]="35-44"
            continue
        if (2022.0-rawdata1["Age"][a] in age_4554):
            rawdata1.loc[a, ["Age"]]="45-54"
            continue
        if (2022.0-rawdata1["Age"][a] in age_5560):
            rawdata1.loc[a, ["Age"]]="55-60"
            continue

In [28]:
rawdata1["Age"].value_counts()

25-34    182
19-24    177
35-44     51
45-54     16
>=18       8
<18        3
>55        1
Name: Age, dtype: int64

#### Change The Nationality to use same format

In [29]:
rawdata1.head()

,Source,Date,Gender,Age,Nationality,Job,Reason/Contribute,Interest,Skills/Experiences/Strengths,Available Time
0,1,2016-05-29,1,25-34,Singaporean,Programme Officer,Believe that refugees deserve equal opportunit...,"Policy change/reform, public outreach, awarene...","Advocacy / Campaigning, Fundraising / Partners...",Evenings; occasionally on weekends
1,1,2016-05-29,2,19-24,Indian,Student,"Learn more about refugees and related issues, ...",Political science,Administration (i.e. data entry / management /...,Flexible
2,1,2016-05-29,1,19-24,Singaporean,Student,"Learn more about refugees and related issues, ...",Law,Policy,flexible
3,1,2016-05-29,1,19-24,Singaporean,Student,"Learn more about refugees and related issues, ...",Raising awareness of the refugee situation loc...,Administration (i.e. data entry / management /...,"flexible, mostly afternoons"
4,1,2016-05-29,2,19-24,Singaporean,Researcher,"Learn more about refugees and related issues, ...","Gender, sociology, human rights and development","Advocacy / Campaigning, Education (i.e. mentor...",Flexible

In [30]:
rawdata1["Nationality"].value_counts()

Singaporean    295
Singapore       25
Indian          11
American         8
Australian       6
              ...
India            1
Afghanistan      1
China            1
Lithuanian       1
Singaporea       1
Name: Nationality, Length: 67, dtype: int64

In [31]:
found=[]
for i in rawdata1.index:
    dat=rawdata1["Nationality"][i]
    if dat.find("Singa")!=-1 and (dat not in found):
        found.append(dat)
        print(dat)
        print(len(rawdata1[rawdata1["Nationality"]==dat]))

Singaporean
295
Indonesian (Singapore PR)
1
Malaysian / Singapore PR
1
Filipino (Singapore PR)
1
Singapore PR, Malaysian
1
Malaysian Citizen / Singapore PR
1
Indian living in Singapore
1
British with Singapore PR
1
Singapore PR (Indian)
1
Singapore
25
Singaporean PR
2
Singaporea
1

In [32]:
rawdata1.loc[rawdata1["Nationality"]=="Indonesian (Singapore PR)", ["Nationality"]]="Indonesian"
rawdata1.loc[rawdata1["Nationality"]=="Indonesian (PR)", ["Nationality"]]="Indonesian"
rawdata1.loc[rawdata1["Nationality"]=="Indonesia", ["Nationality"]]="Indonesian"
rawdata1.loc[rawdata1["Nationality"]=="INDONESIAN", ["Nationality"]]="Indonesian"
rawdata1.loc[rawdata1["Nationality"]=="Malaysian / Singapore PR", ["Nationality"]]="Malaysian"
rawdata1.loc[rawdata1["Nationality"]=="Filipino (Singapore PR)", ["Nationality"]]="Filipino"
rawdata1.loc[rawdata1["Nationality"]=="Malaysian Citizen / Singapore PR", ["Nationality"]]="Malaysian"
rawdata1.loc[rawdata1["Nationality"]=="Singapore PR, Malaysian", ["Nationality"]]="Malaysian"
rawdata1.loc[rawdata1["Nationality"]=="Indian living in Singapore", ["Nationality"]]="Indian"
rawdata1.loc[rawdata1["Nationality"]=="British with Singapore PR", ["Nationality"]]="British"
rawdata1.loc[rawdata1["Nationality"]=="Singapore PR (Indian)", ["Nationality"]]="Indian"
rawdata1.loc[rawdata1["Nationality"]=="INDIAN", ["Nationality"]]="Indian"
rawdata1.loc[rawdata1["Nationality"]=="Singaporea", ["Nationality"]]="Singaporean"
rawdata1.loc[rawdata1["Nationality"]=="Malaysian (SG PR)", ["Nationality"]]="Malaysian"
rawdata1.loc[rawdata1["Nationality"]=="Malaysian (SPR)", ["Nationality"]]="Malaysian"
rawdata1.loc[rawdata1["Nationality"]=="Malaysian (Work Permit Holder)", ["Nationality"]]="Malaysian"
rawdata1.loc[rawdata1["Nationality"]=="MALAYSIAN", ["Nationality"]]="Malaysian"
rawdata1.loc[rawdata1["Nationality"]=="Singapore", ["Nationality"]]="Singaporean"
rawdata1.loc[rawdata1["Nationality"]=="Singaporean PR", ["Nationality"]]="Singaporean"
rawdata1.loc[rawdata1["Nationality"]=="USA", ["Nationality"]]="American"
rawdata1.loc[rawdata1["Nationality"]=="US Citizen, SG Resident", ["Nationality"]]="American"
rawdata1.loc[rawdata1["Nationality"]=="Filipino (SPR)", ["Nationality"]]="Filipino"
rawdata1.loc[rawdata1["Nationality"]=="UK", ["Nationality"]]="British"
rawdata1.loc[rawdata1["Nationality"]=="British/Spanish", ["Nationality"]]="British"
rawdata1.loc[rawdata1["Nationality"]=="Australian / Syrian", ["Nationality"]]="Australian"
rawdata1.loc[rawdata1["Nationality"]=="American USA", ["Nationality"]]="American"
rawdata1.loc[rawdata1["Nationality"]=="France", ["Nationality"]]="French"
rawdata1.loc[rawdata1["Nationality"]=="Student Pass", ["Nationality"]]="Others"
rawdata1.loc[rawdata1["Nationality"]=="-", ["Nationality"]]="Others"
rawdata1.loc[rawdata1["Nationality"]=="US", ["Nationality"]]="American"
rawdata1.loc[rawdata1["Nationality"]=="swiss", ["Nationality"]]="Swiss"
rawdata1.loc[rawdata1["Nationality"]=="Chinese", ["Nationality"]]="China"
rawdata1.loc[rawdata1["Nationality"]=="India", ["Nationality"]]="Indian"
rawdata1.loc[rawdata1["Nationality"]=="Afghan", ["Nationality"]]="Afghanistan"
rawdata1.loc[rawdata1["Nationality"]=="Hong Kong", ["Nationality"]]="HongKong"

In [33]:
rawdata1["Nationality"].value_counts()

Singaporean    323
Indian          16
American        15
Malaysian       12
Indonesian       9
British          8
Australian       7
Filipino         6
Canadian         5
French           5
Others           4
China            2
Afghanistan      2
Russian          2
Myanmar          2
Spanish          2
Turkey           1
Bangladeshi      1
Zimbabwe         1
South Korea      1
Thailand         1
Pakistan         1
Taiwanese        1
Bruneian         1
Dutch            1
Nigerian         1
Lithuanian       1
Romanian         1
German           1
Thai             1
Swiss            1
Sri Lankan       1
HongKong         1
Japan            1
Name: Nationality, dtype: int64

In [34]:
rawdata1["Nationality"].value_counts().sort_index(ascending=True)

Afghanistan      2
American        15
Australian       7
Bangladeshi      1
British          8
Bruneian         1
Canadian         5
China            2
Dutch            1
Filipino         6
French           5
German           1
HongKong         1
Indian          16
Indonesian       9
Japan            1
Lithuanian       1
Malaysian       12
Myanmar          2
Nigerian         1
Others           4
Pakistan         1
Romanian         1
Russian          2
Singaporean    323
South Korea      1
Spanish          2
Sri Lankan       1
Swiss            1
Taiwanese        1
Thai             1
Thailand         1
Turkey           1
Zimbabwe         1
Name: Nationality, dtype: int64

#### Change the Job Format

In [35]:
rawdata1.head()

,Source,Date,Gender,Age,Nationality,Job,Reason/Contribute,Interest,Skills/Experiences/Strengths,Available Time
0,1,2016-05-29,1,25-34,Singaporean,Programme Officer,Believe that refugees deserve equal opportunit...,"Policy change/reform, public outreach, awarene...","Advocacy / Campaigning, Fundraising / Partners...",Evenings; occasionally on weekends
1,1,2016-05-29,2,19-24,Indian,Student,"Learn more about refugees and related issues, ...",Political science,Administration (i.e. data entry / management /...,Flexible
2,1,2016-05-29,1,19-24,Singaporean,Student,"Learn more about refugees and related issues, ...",Law,Policy,flexible
3,1,2016-05-29,1,19-24,Singaporean,Student,"Learn more about refugees and related issues, ...",Raising awareness of the refugee situation loc...,Administration (i.e. data entry / management /...,"flexible, mostly afternoons"
4,1,2016-05-29,2,19-24,Singaporean,Researcher,"Learn more about refugees and related issues, ...","Gender, sociology, human rights and development","Advocacy / Campaigning, Education (i.e. mentor...",Flexible

In [36]:
rawdata1["Job"].value_counts()

Student                               125
Lawyer                                  8
Teacher                                 7
Researcher                              6
Research Assistant                      5
                                     ...
Project and Export Finance Advisor      1
Parkour and Tactical Instructor         1
Nil                                     1
Research Associate, NUS                 1
Product Policy Manager                  1
Name: Job, Length: 249, dtype: int64

In [37]:
found=[]
for i in rawdata1.index:
    dat=rawdata1["Job"][i]
    if dat.find("Stude")!=-1 and (dat not in found):
        found.append(dat)
        print(dat)
        print(len(rawdata1[rawdata1["Job"]==dat]))

Student
125
University Student
3
Research Assistant/PhD Student
1
Student at NUS
1
Graduate Student (Law)
1
Student- University
1
Student/ AIESECer/ Youth Corps Leader
1
Student (Uni)
1
Undergraduate Student
1
Graduate Student
1
Medical Student
1
Student (in my final sem!:))
1
NUS Student
1
Student (Y4 Global Studies and Sociology Undergrad @ NUS)
1
Masters Student
1
Student (4th year, with a major in Political Science and a minor in History)
1
Education Consultant, and Doctoral Student Researcher
1
Master's Student
1
Student (NSF)
1

In [77]:
rawdata1.loc[rawdata1["Job"]=="University Student", ["Job"]]="Student"
rawdata1.loc[rawdata1["Job"]=="Research Assistant/PhD Student", ["Job"]]="Student"
rawdata1.loc[rawdata1["Job"]=="Student at NUS", ["Job"]]="Student"
rawdata1.loc[rawdata1["Job"]=="Graduate Student (Law)", ["Job"]]="Student"
rawdata1.loc[rawdata1["Job"]=="Student- University", ["Job"]]="Student"
rawdata1.loc[rawdata1["Job"]=="Student/ AIESECer/ Youth Corps Leader", ["Job"]]="Student"
rawdata1.loc[rawdata1["Job"]=="Student (Uni)", ["Job"]]="Student"
rawdata1.loc[rawdata1["Job"]=="Undergraduate Student", ["Job"]]="Student"
rawdata1.loc[rawdata1["Job"]=="Graduate Student", ["Job"]]="Student"
rawdata1.loc[rawdata1["Job"]=="Medical Student", ["Job"]]="Student"
rawdata1.loc[rawdata1["Job"]=="Student (in my final sem!:))", ["Job"]]="Student"
rawdata1.loc[rawdata1["Job"]=="NUS Student", ["Job"]]="Student"
rawdata1.loc[rawdata1["Job"]=="Student (Y4 Global Studies and Sociology Undergrad @ NUS)", ["Job"]]="Student"
rawdata1.loc[rawdata1["Job"]=="Masters Student", ["Job"]]="Student"
rawdata1.loc[rawdata1["Job"]=="Student (4th year, with a major in Political Science and a minor in History)", ["Job"]]="Student"
rawdata1.loc[rawdata1["Job"]=="Education Consultant, and Doctoral Student Researcher", ["Job"]]="Student"
rawdata1.loc[rawdata1["Job"]=="Master's Student", ["Job"]]="Student"
rawdata1.loc[rawdata1["Job"]=="Indonesian (Singapore PR)", ["Job"]]="Student"
rawdata1.loc[rawdata1["Job"]=="Student (NSF)", ["Job"]]="Student"
rawdata1.loc[rawdata1["Job"]=="university student", ["Job"]]="Student"
rawdata1.loc[rawdata1["Job"]=="Engineer, PhD student", ["Job"]]="Student"
rawdata1.loc[rawdata1["Job"]=="Master's student (Euroculture) at the University of Groningen with a Bachelor's in Minorities and multilingualism", ["Job"]]="Student"
rawdata1.loc[rawdata1["Job"]=="Undergraduate student", ["Job"]]="Student"
rawdata1.loc[rawdata1["Job"]=="Social Sciences undergrad", ["Job"]]="Student"
rawdata1.loc[rawdata1["Job"]=="undergraduate (full-time)", ["Job"]]="Student"
rawdata1.loc[rawdata1["Job"]=="Industrial Design Undergraduate", ["Job"]]="Student"
rawdata1.loc[rawdata1["Job"]=="UNHCR Intern/Undergraduate", ["Job"]]="Student"
rawdata1.loc[rawdata1["Job"]=="Undergraduate", ["Job"]]="Student"
rawdata1.loc[rawdata1["Job"]=="Gender Specialist and Program Trainer & a criminology student", ["Job"]]="Student"

In [78]:
rawdata1["Job"].value_counts()

Student                                 157
Researcher                               21
Teacher                                  15
Lawyer                                    8
Journalist                                4
                                       ...
Nil                                       1
Media (Journalist)                        1
Senior Executive - Alumni and Events      1
Procurement Manager                       1
Product Policy Manager                    1
Name: Job, Length: 202, dtype: int64

In [79]:
found=[]
for i in rawdata1.index:
    dat=rawdata1["Job"][i]
    if dat.find("cher")!=-1 and (dat not in found):
        found.append(dat)
        print(dat)
        print(len(rawdata1[rawdata1["Job"]==dat]))

Researcher
21
Teacher
15

In [80]:
rawdata1.loc[rawdata1["Job"]=="Social Researchert", ["Job"]]="Researcher"
rawdata1.loc[rawdata1["Job"]=="Chinese Language Teacher, Insurance Agent, Scuba Diving Instructor", ["Job"]]="Teacher"
rawdata1.loc[rawdata1["Job"]=="High school English teacher (UWCSEA)", ["Job"]]="Teacher"
rawdata1.loc[rawdata1["Job"]=="Preschool teacher", ["Job"]]="Teacher"
rawdata1.loc[rawdata1["Job"]=="Language teacher", ["Job"]]="Teacher"
rawdata1.loc[rawdata1["Job"]=="Teacher, Research Analyst", ["Job"]]="Teacher"
rawdata1.loc[rawdata1["Job"]=="Art Teacher", ["Job"]]="Teacher"
rawdata1.loc[rawdata1["Job"]=="English Teacher", ["Job"]]="Teacher"
rawdata1.loc[rawdata1["Job"]=="teacher, researcher", ["Job"]]="Teacher"

In [82]:
rawdata1["Job"].value_counts()

Student                                 157
Researcher                               21
Teacher                                  15
Lawyer                                    8
Journalist                                4
                                       ...
Nil                                       1
Media (Journalist)                        1
Senior Executive - Alumni and Events      1
Procurement Manager                       1
Product Policy Manager                    1
Name: Job, Length: 202, dtype: int64

In [83]:
found=[]
for i in rawdata1.index:
    dat=rawdata1["Job"][i]
    if dat.find("Rese")!=-1 and (dat not in found):
        found.append(dat)
        print(dat)
        print(len(rawdata1[rawdata1["Job"]==dat]))

Researcher
21

In [84]:
rawdata1.loc[rawdata1["Job"]=="Social Researcher", ["Job"]]="Researcher"
rawdata1.loc[rawdata1["Job"]=="Research Assistant", ["Job"]]="Researcher"
rawdata1.loc[rawdata1["Job"]=="Research Coordinator", ["Job"]]="Researcher"
rawdata1.loc[rawdata1["Job"]=="Research Fellow", ["Job"]]="Researcher"
rawdata1.loc[rawdata1["Job"]=="Research Associate, NUS", ["Job"]]="Researcher"
rawdata1.loc[rawdata1["Job"]=="Research", ["Job"]]="Researcher"
rawdata1.loc[rawdata1["Job"]=="Legal Research Associate", ["Job"]]="Researcher"
rawdata1.loc[rawdata1["Job"]=="Clinical Research Coordinator", ["Job"]]="Researcher"
rawdata1.loc[rawdata1["Job"]=="Research coordinator", ["Job"]]="Researcher"
rawdata1.loc[rawdata1["Job"]=="PhD Research Fellow", ["Job"]]="Researcher"
rawdata1.loc[rawdata1["Job"]=="Research Analyst", ["Job"]]="Researcher"

In [85]:
rawdata1["Job"].value_counts()

Student                                 157
Researcher                               21
Teacher                                  15
Lawyer                                    8
Journalist                                4
                                       ...
Nil                                       1
Media (Journalist)                        1
Senior Executive - Alumni and Events      1
Procurement Manager                       1
Product Policy Manager                    1
Name: Job, Length: 202, dtype: int64

In [89]:
found=[]
for i in rawdata1.index:
    dat=rawdata1["Job"][i]
    if dat.find("Manager")!=-1 and (dat not in found):
        found.append(dat)
        print(dat)
        print(len(rawdata1[rawdata1["Job"]==dat]))

Fundraising Manager
1
Manager, Foundation
1
Programme Manager (NPO)
1
Manager, Ministry of Home Affairs
1
Communications Manager
2
IT Manager
1
Procurement Manager
1
Manager of Engineering
1
Bank Project Manager
1
Manager
2
Marketing Manager
1
Arts Manager
1
Engineering Manager
1
Social Media Manager
1
Business Manager
1
Assistant Manager
1
Global Mobility Manager
1
HR Manager
1
Product Policy Manager
1